pipeline {
    agent { 
         node {
            label 'agent-docker'
            customWorkspace '/home/vant/jenkins-agent-workspace/cd-bluegreen-rollback'
        }
   }

    environment {
       COMPOSE_PROJECT_NAME = "jenkins-docker-cd-rollback"
    }
    
    options {
        timestamps()
        disableConcurrentBuilds()
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Permissions') {
            steps {
                sh 'chmod +x scripts/*.sh'
            }
        }
        
        stage('Start stack') {
            steps {
                sh '''
                  docker compose -p "$COMPOSE_PROJECT_NAME" up -d --build app_blue app_green nginx
                  docker compose -p "$COMPOSE_PROJECT_NAME" ps
                '''
            }
        }

        stage('Deploy with gate + rollback') {
            steps {
                sh '''
                 test -x ./scripts/deploy.sh || { echo "deploy.sh not found or not executable"; exit 1; }
                 ./scripts/deploy.sh
                '''
            }
        }
    }
    
    post {
        always {
            sh '''
                echo "Final active version:"
                docker run --rm --network "${COMPOSE_PROJECT_NAME}_default" curlimages/curl:8.7.1 -fsS http://nginx/version || true

                echo "Compose status:"
                docker compose -p "$COMPOSE_PROJECT_NAME" ps || true
            '''
        }

        cleanup {
            sh '''
                echo "Cleaning up stack..."
                docker compose -p "$COMPOSE_PROJECT_NAME" stop app_blue app_green nginx || true
            '''
        }
    }

}