pipeline {
    agent { label 'docker' }

    environment {
       COMPOSE_PROJECT_NAME = "cd-bluegreen"
    }
    
    options {
        timestamps()
        disableConcurrentBuilds()
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Permissions') {
            steps {
                sh 'chmod +x scripts/*.sh'
            }
        }
        
        stage('Start stack') {
            steps {
                sh '''
                  docker compose -p "$COMPOSE_PROJECT_NAME" up -d --build app_blue app_green nginx
                  docker compose -p "$COMPOSE_PROJECT_NAME" ps
                '''
            }
        }

        stage('Deploy with gate + rollback') {
            steps {
                sh '''
                 test -x ./scripts/deploy.sh || { echo "deploy.sh not found or not executable"; exit 1; }
                 ./scripts/deploy.sh
                '''
            }
        }
    }
    
    post {
        always {
            sh '''
                echo "Final active version (via nginx container):"
                docker compose -p "$COMPOSE_PROJECT_NAME" exec -T nginx sh -lc 'curl -s http://localhost/version; echo' || true

                echo "Compose status:"
                docker compose -p "$COMPOSE_PROJECT_NAME" ps || true
            '''
        }

        cleanup {
            sh '''
                echo "Cleaning up stack..."
                docker compose -p "$COMPOSE_PROJECT_NAME" down --volumes --remove-orphans || true
            '''
        }
    }

}